### ISSUE TITLE
debian/ubuntu like dependencies as periodic-table fails to start

### ISSUE THREAD

**Issue by Ark74** [cristian99garcia/periodic-table#15]
Hi!
I'm working on trisquel-sugar 10.0 based on ubuntu 20.04, I'm fairly new to still we are backporting sugar from impish, so we have the latest fixes available.

I'm having a small issue with this activity, is there some recommended debian dependencies that should be fulfilled, some other 45 activities are working fine, so I guess most should be there.

Or maybe it's something else, but I don't see any specific log or error that I can share.

Any advice is very welcome.

**Comment by quozl** [comment]
Why does the activity fail to start?  Logs are put in .sugar/default/logs and are named by activity bundle.

**Comment by quozl** [comment]
Among the collection of activities, this activity is fairly unique in having a dependency on Evince through the GObject introspection framework.  Check if you have GObject introspection data for the evince libraries installed.

**Comment by Ark74** [comment]
Oh! I missed that one file, you're completely right!
evince was missing on my installation, checking now with `gir1.2-evince-3.0`

**Comment by Ark74** [comment]
@quozl  that was it!
I was missing that one, thanks!

Do I need evince too, or just `gir1.2-evince-3.0` ?

**Comment by quozl** [comment]
No idea.  The code refers to Evince through the GObject introspection methods, so probably not.

**Comment by quozl** [comment]
Opportunity to add this dependency to README.md if anyone is interested.  I've no time right now.

**Comment by Ark74** [comment]
Ok, that's it, thank you very much.
I'm getting closer.

**Comment by Ark74** [comment]
@quozl done in #16
